// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CalculationsColumns holds the columns for the "calculations" table.
	CalculationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "card_id", Type: field.TypeUUID},
		{Name: "magic_id", Type: field.TypeUUID},
		{Name: "card_ratio", Type: field.TypeInt32},
		{Name: "magic_ratio", Type: field.TypeInt32},
	}
	// CalculationsTable holds the schema information for the "calculations" table.
	CalculationsTable = &schema.Table{
		Name:       "calculations",
		Columns:    CalculationsColumns,
		PrimaryKey: []*schema.Column{CalculationsColumns[0]},
	}
	// CardsColumns holds the columns for the "cards" table.
	CardsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Unique: true},
	}
	// CardsTable holds the schema information for the "cards" table.
	CardsTable = &schema.Table{
		Name:       "cards",
		Columns:    CardsColumns,
		PrimaryKey: []*schema.Column{CardsColumns[0]},
	}
	// MagicsColumns holds the columns for the "magics" table.
	MagicsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Unique: true},
	}
	// MagicsTable holds the schema information for the "magics" table.
	MagicsTable = &schema.Table{
		Name:       "magics",
		Columns:    MagicsColumns,
		PrimaryKey: []*schema.Column{MagicsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CalculationsTable,
		CardsTable,
		MagicsTable,
	}
)

func init() {
}
