// Code generated by entc, DO NOT EDIT.

package database

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/iamnande/cardmod/internal/database/limitbreak"
	"github.com/iamnande/cardmod/internal/database/predicate"
)

// LimitBreakQuery is the builder for querying LimitBreak entities.
type LimitBreakQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.LimitBreak
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LimitBreakQuery builder.
func (lbq *LimitBreakQuery) Where(ps ...predicate.LimitBreak) *LimitBreakQuery {
	lbq.predicates = append(lbq.predicates, ps...)
	return lbq
}

// Limit adds a limit step to the query.
func (lbq *LimitBreakQuery) Limit(limit int) *LimitBreakQuery {
	lbq.limit = &limit
	return lbq
}

// Offset adds an offset step to the query.
func (lbq *LimitBreakQuery) Offset(offset int) *LimitBreakQuery {
	lbq.offset = &offset
	return lbq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (lbq *LimitBreakQuery) Unique(unique bool) *LimitBreakQuery {
	lbq.unique = &unique
	return lbq
}

// Order adds an order step to the query.
func (lbq *LimitBreakQuery) Order(o ...OrderFunc) *LimitBreakQuery {
	lbq.order = append(lbq.order, o...)
	return lbq
}

// First returns the first LimitBreak entity from the query.
// Returns a *NotFoundError when no LimitBreak was found.
func (lbq *LimitBreakQuery) First(ctx context.Context) (*LimitBreak, error) {
	nodes, err := lbq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{limitbreak.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (lbq *LimitBreakQuery) FirstX(ctx context.Context) *LimitBreak {
	node, err := lbq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LimitBreak ID from the query.
// Returns a *NotFoundError when no LimitBreak ID was found.
func (lbq *LimitBreakQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lbq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{limitbreak.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (lbq *LimitBreakQuery) FirstIDX(ctx context.Context) int {
	id, err := lbq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LimitBreak entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one LimitBreak entity is not found.
// Returns a *NotFoundError when no LimitBreak entities are found.
func (lbq *LimitBreakQuery) Only(ctx context.Context) (*LimitBreak, error) {
	nodes, err := lbq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{limitbreak.Label}
	default:
		return nil, &NotSingularError{limitbreak.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (lbq *LimitBreakQuery) OnlyX(ctx context.Context) *LimitBreak {
	node, err := lbq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LimitBreak ID in the query.
// Returns a *NotSingularError when exactly one LimitBreak ID is not found.
// Returns a *NotFoundError when no entities are found.
func (lbq *LimitBreakQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lbq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{limitbreak.Label}
	default:
		err = &NotSingularError{limitbreak.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (lbq *LimitBreakQuery) OnlyIDX(ctx context.Context) int {
	id, err := lbq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LimitBreaks.
func (lbq *LimitBreakQuery) All(ctx context.Context) ([]*LimitBreak, error) {
	if err := lbq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return lbq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (lbq *LimitBreakQuery) AllX(ctx context.Context) []*LimitBreak {
	nodes, err := lbq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LimitBreak IDs.
func (lbq *LimitBreakQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := lbq.Select(limitbreak.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (lbq *LimitBreakQuery) IDsX(ctx context.Context) []int {
	ids, err := lbq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (lbq *LimitBreakQuery) Count(ctx context.Context) (int, error) {
	if err := lbq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return lbq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (lbq *LimitBreakQuery) CountX(ctx context.Context) int {
	count, err := lbq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (lbq *LimitBreakQuery) Exist(ctx context.Context) (bool, error) {
	if err := lbq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return lbq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (lbq *LimitBreakQuery) ExistX(ctx context.Context) bool {
	exist, err := lbq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LimitBreakQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (lbq *LimitBreakQuery) Clone() *LimitBreakQuery {
	if lbq == nil {
		return nil
	}
	return &LimitBreakQuery{
		config:     lbq.config,
		limit:      lbq.limit,
		offset:     lbq.offset,
		order:      append([]OrderFunc{}, lbq.order...),
		predicates: append([]predicate.LimitBreak{}, lbq.predicates...),
		// clone intermediate query.
		sql:  lbq.sql.Clone(),
		path: lbq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LimitBreak.Query().
//		GroupBy(limitbreak.FieldName).
//		Aggregate(database.Count()).
//		Scan(ctx, &v)
//
func (lbq *LimitBreakQuery) GroupBy(field string, fields ...string) *LimitBreakGroupBy {
	group := &LimitBreakGroupBy{config: lbq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := lbq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return lbq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.LimitBreak.Query().
//		Select(limitbreak.FieldName).
//		Scan(ctx, &v)
//
func (lbq *LimitBreakQuery) Select(fields ...string) *LimitBreakSelect {
	lbq.fields = append(lbq.fields, fields...)
	return &LimitBreakSelect{LimitBreakQuery: lbq}
}

func (lbq *LimitBreakQuery) prepareQuery(ctx context.Context) error {
	for _, f := range lbq.fields {
		if !limitbreak.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("database: invalid field %q for query", f)}
		}
	}
	if lbq.path != nil {
		prev, err := lbq.path(ctx)
		if err != nil {
			return err
		}
		lbq.sql = prev
	}
	return nil
}

func (lbq *LimitBreakQuery) sqlAll(ctx context.Context) ([]*LimitBreak, error) {
	var (
		nodes = []*LimitBreak{}
		_spec = lbq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &LimitBreak{config: lbq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("database: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, lbq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (lbq *LimitBreakQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := lbq.querySpec()
	return sqlgraph.CountNodes(ctx, lbq.driver, _spec)
}

func (lbq *LimitBreakQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := lbq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("database: check existence: %w", err)
	}
	return n > 0, nil
}

func (lbq *LimitBreakQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   limitbreak.Table,
			Columns: limitbreak.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: limitbreak.FieldID,
			},
		},
		From:   lbq.sql,
		Unique: true,
	}
	if unique := lbq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := lbq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, limitbreak.FieldID)
		for i := range fields {
			if fields[i] != limitbreak.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := lbq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := lbq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := lbq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := lbq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (lbq *LimitBreakQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(lbq.driver.Dialect())
	t1 := builder.Table(limitbreak.Table)
	columns := lbq.fields
	if len(columns) == 0 {
		columns = limitbreak.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if lbq.sql != nil {
		selector = lbq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range lbq.predicates {
		p(selector)
	}
	for _, p := range lbq.order {
		p(selector)
	}
	if offset := lbq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := lbq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LimitBreakGroupBy is the group-by builder for LimitBreak entities.
type LimitBreakGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lbgb *LimitBreakGroupBy) Aggregate(fns ...AggregateFunc) *LimitBreakGroupBy {
	lbgb.fns = append(lbgb.fns, fns...)
	return lbgb
}

// Scan applies the group-by query and scans the result into the given value.
func (lbgb *LimitBreakGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := lbgb.path(ctx)
	if err != nil {
		return err
	}
	lbgb.sql = query
	return lbgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (lbgb *LimitBreakGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := lbgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (lbgb *LimitBreakGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(lbgb.fields) > 1 {
		return nil, errors.New("database: LimitBreakGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := lbgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (lbgb *LimitBreakGroupBy) StringsX(ctx context.Context) []string {
	v, err := lbgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lbgb *LimitBreakGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = lbgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{limitbreak.Label}
	default:
		err = fmt.Errorf("database: LimitBreakGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (lbgb *LimitBreakGroupBy) StringX(ctx context.Context) string {
	v, err := lbgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (lbgb *LimitBreakGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(lbgb.fields) > 1 {
		return nil, errors.New("database: LimitBreakGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := lbgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (lbgb *LimitBreakGroupBy) IntsX(ctx context.Context) []int {
	v, err := lbgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lbgb *LimitBreakGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = lbgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{limitbreak.Label}
	default:
		err = fmt.Errorf("database: LimitBreakGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (lbgb *LimitBreakGroupBy) IntX(ctx context.Context) int {
	v, err := lbgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (lbgb *LimitBreakGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(lbgb.fields) > 1 {
		return nil, errors.New("database: LimitBreakGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := lbgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (lbgb *LimitBreakGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := lbgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lbgb *LimitBreakGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = lbgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{limitbreak.Label}
	default:
		err = fmt.Errorf("database: LimitBreakGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (lbgb *LimitBreakGroupBy) Float64X(ctx context.Context) float64 {
	v, err := lbgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (lbgb *LimitBreakGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(lbgb.fields) > 1 {
		return nil, errors.New("database: LimitBreakGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := lbgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (lbgb *LimitBreakGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := lbgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lbgb *LimitBreakGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = lbgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{limitbreak.Label}
	default:
		err = fmt.Errorf("database: LimitBreakGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (lbgb *LimitBreakGroupBy) BoolX(ctx context.Context) bool {
	v, err := lbgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (lbgb *LimitBreakGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range lbgb.fields {
		if !limitbreak.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := lbgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lbgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (lbgb *LimitBreakGroupBy) sqlQuery() *sql.Selector {
	selector := lbgb.sql.Select()
	aggregation := make([]string, 0, len(lbgb.fns))
	for _, fn := range lbgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(lbgb.fields)+len(lbgb.fns))
		for _, f := range lbgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(lbgb.fields...)...)
}

// LimitBreakSelect is the builder for selecting fields of LimitBreak entities.
type LimitBreakSelect struct {
	*LimitBreakQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (lbs *LimitBreakSelect) Scan(ctx context.Context, v interface{}) error {
	if err := lbs.prepareQuery(ctx); err != nil {
		return err
	}
	lbs.sql = lbs.LimitBreakQuery.sqlQuery(ctx)
	return lbs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (lbs *LimitBreakSelect) ScanX(ctx context.Context, v interface{}) {
	if err := lbs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (lbs *LimitBreakSelect) Strings(ctx context.Context) ([]string, error) {
	if len(lbs.fields) > 1 {
		return nil, errors.New("database: LimitBreakSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := lbs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (lbs *LimitBreakSelect) StringsX(ctx context.Context) []string {
	v, err := lbs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (lbs *LimitBreakSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = lbs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{limitbreak.Label}
	default:
		err = fmt.Errorf("database: LimitBreakSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (lbs *LimitBreakSelect) StringX(ctx context.Context) string {
	v, err := lbs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (lbs *LimitBreakSelect) Ints(ctx context.Context) ([]int, error) {
	if len(lbs.fields) > 1 {
		return nil, errors.New("database: LimitBreakSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := lbs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (lbs *LimitBreakSelect) IntsX(ctx context.Context) []int {
	v, err := lbs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (lbs *LimitBreakSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = lbs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{limitbreak.Label}
	default:
		err = fmt.Errorf("database: LimitBreakSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (lbs *LimitBreakSelect) IntX(ctx context.Context) int {
	v, err := lbs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (lbs *LimitBreakSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(lbs.fields) > 1 {
		return nil, errors.New("database: LimitBreakSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := lbs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (lbs *LimitBreakSelect) Float64sX(ctx context.Context) []float64 {
	v, err := lbs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (lbs *LimitBreakSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = lbs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{limitbreak.Label}
	default:
		err = fmt.Errorf("database: LimitBreakSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (lbs *LimitBreakSelect) Float64X(ctx context.Context) float64 {
	v, err := lbs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (lbs *LimitBreakSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(lbs.fields) > 1 {
		return nil, errors.New("database: LimitBreakSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := lbs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (lbs *LimitBreakSelect) BoolsX(ctx context.Context) []bool {
	v, err := lbs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (lbs *LimitBreakSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = lbs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{limitbreak.Label}
	default:
		err = fmt.Errorf("database: LimitBreakSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (lbs *LimitBreakSelect) BoolX(ctx context.Context) bool {
	v, err := lbs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (lbs *LimitBreakSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := lbs.sql.Query()
	if err := lbs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
