// Code generated by entc, DO NOT EDIT.

package database

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/iamnande/cardmod/internal/database/limitbreak"
	"github.com/iamnande/cardmod/internal/database/predicate"
)

// LimitBreakDelete is the builder for deleting a LimitBreak entity.
type LimitBreakDelete struct {
	config
	hooks    []Hook
	mutation *LimitBreakMutation
}

// Where appends a list predicates to the LimitBreakDelete builder.
func (lbd *LimitBreakDelete) Where(ps ...predicate.LimitBreak) *LimitBreakDelete {
	lbd.mutation.Where(ps...)
	return lbd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (lbd *LimitBreakDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(lbd.hooks) == 0 {
		affected, err = lbd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LimitBreakMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			lbd.mutation = mutation
			affected, err = lbd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(lbd.hooks) - 1; i >= 0; i-- {
			if lbd.hooks[i] == nil {
				return 0, fmt.Errorf("database: uninitialized hook (forgotten import database/runtime?)")
			}
			mut = lbd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, lbd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (lbd *LimitBreakDelete) ExecX(ctx context.Context) int {
	n, err := lbd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (lbd *LimitBreakDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: limitbreak.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: limitbreak.FieldID,
			},
		},
	}
	if ps := lbd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, lbd.driver, _spec)
}

// LimitBreakDeleteOne is the builder for deleting a single LimitBreak entity.
type LimitBreakDeleteOne struct {
	lbd *LimitBreakDelete
}

// Exec executes the deletion query.
func (lbdo *LimitBreakDeleteOne) Exec(ctx context.Context) error {
	n, err := lbdo.lbd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{limitbreak.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (lbdo *LimitBreakDeleteOne) ExecX(ctx context.Context) {
	lbdo.lbd.ExecX(ctx)
}
