// Code generated by entc, DO NOT EDIT.

package database

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/iamnande/cardmod/internal/database/limitbreak"
)

// LimitBreakCreate is the builder for creating a LimitBreak entity.
type LimitBreakCreate struct {
	config
	mutation *LimitBreakMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (lbc *LimitBreakCreate) SetName(s string) *LimitBreakCreate {
	lbc.mutation.SetName(s)
	return lbc
}

// Mutation returns the LimitBreakMutation object of the builder.
func (lbc *LimitBreakCreate) Mutation() *LimitBreakMutation {
	return lbc.mutation
}

// Save creates the LimitBreak in the database.
func (lbc *LimitBreakCreate) Save(ctx context.Context) (*LimitBreak, error) {
	var (
		err  error
		node *LimitBreak
	)
	if len(lbc.hooks) == 0 {
		if err = lbc.check(); err != nil {
			return nil, err
		}
		node, err = lbc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LimitBreakMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = lbc.check(); err != nil {
				return nil, err
			}
			lbc.mutation = mutation
			if node, err = lbc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(lbc.hooks) - 1; i >= 0; i-- {
			if lbc.hooks[i] == nil {
				return nil, fmt.Errorf("database: uninitialized hook (forgotten import database/runtime?)")
			}
			mut = lbc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, lbc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (lbc *LimitBreakCreate) SaveX(ctx context.Context) *LimitBreak {
	v, err := lbc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lbc *LimitBreakCreate) Exec(ctx context.Context) error {
	_, err := lbc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lbc *LimitBreakCreate) ExecX(ctx context.Context) {
	if err := lbc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lbc *LimitBreakCreate) check() error {
	if _, ok := lbc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`database: missing required field "name"`)}
	}
	if v, ok := lbc.mutation.Name(); ok {
		if err := limitbreak.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`database: validator failed for field "name": %w`, err)}
		}
	}
	return nil
}

func (lbc *LimitBreakCreate) sqlSave(ctx context.Context) (*LimitBreak, error) {
	_node, _spec := lbc.createSpec()
	if err := sqlgraph.CreateNode(ctx, lbc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (lbc *LimitBreakCreate) createSpec() (*LimitBreak, *sqlgraph.CreateSpec) {
	var (
		_node = &LimitBreak{config: lbc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: limitbreak.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: limitbreak.FieldID,
			},
		}
	)
	if value, ok := lbc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: limitbreak.FieldName,
		})
		_node.Name = value
	}
	return _node, _spec
}

// LimitBreakCreateBulk is the builder for creating many LimitBreak entities in bulk.
type LimitBreakCreateBulk struct {
	config
	builders []*LimitBreakCreate
}

// Save creates the LimitBreak entities in the database.
func (lbcb *LimitBreakCreateBulk) Save(ctx context.Context) ([]*LimitBreak, error) {
	specs := make([]*sqlgraph.CreateSpec, len(lbcb.builders))
	nodes := make([]*LimitBreak, len(lbcb.builders))
	mutators := make([]Mutator, len(lbcb.builders))
	for i := range lbcb.builders {
		func(i int, root context.Context) {
			builder := lbcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LimitBreakMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, lbcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, lbcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, lbcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (lbcb *LimitBreakCreateBulk) SaveX(ctx context.Context) []*LimitBreak {
	v, err := lbcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lbcb *LimitBreakCreateBulk) Exec(ctx context.Context) error {
	_, err := lbcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lbcb *LimitBreakCreateBulk) ExecX(ctx context.Context) {
	if err := lbcb.Exec(ctx); err != nil {
		panic(err)
	}
}
