project_name: cardmod-api
builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - linux
      - darwin
    ldflags:
      - -s -w -X main.ServiceVersion={{.Version}}
    main: ./cmd/cardmodd/main.go
dist: build
