version: '3.9'
services:

  # api
  api:
    image: cardmod/api:local
    container_name: cardmod_api
    build:
      context: .
      dockerfile: cmd/cardmodd/Dockerfile
    ports:
      - 9000:9000