// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Card is the predicate function for card builders.
type Card func(*sql.Selector)

// Item is the predicate function for item builders.
type Item func(*sql.Selector)

// LimitBreak is the predicate function for limitbreak builders.
type LimitBreak func(*sql.Selector)

// Magic is the predicate function for magic builders.
type Magic func(*sql.Selector)
