// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: iamnande/cardmod/magic/v1/api.proto

package magicv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request schema for the GetMagic request.
type GetMagicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name of the magic to get.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetMagicRequest) Reset() {
	*x = GetMagicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iamnande_cardmod_magic_v1_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMagicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMagicRequest) ProtoMessage() {}

func (x *GetMagicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iamnande_cardmod_magic_v1_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMagicRequest.ProtoReflect.Descriptor instead.
func (*GetMagicRequest) Descriptor() ([]byte, []int) {
	return file_iamnande_cardmod_magic_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetMagicRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request schema for the ListMagics request.
// TODO: pagination, filtering, and sorting
type ListMagicsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListMagicsRequest) Reset() {
	*x = ListMagicsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iamnande_cardmod_magic_v1_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMagicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMagicsRequest) ProtoMessage() {}

func (x *ListMagicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iamnande_cardmod_magic_v1_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMagicsRequest.ProtoReflect.Descriptor instead.
func (*ListMagicsRequest) Descriptor() ([]byte, []int) {
	return file_iamnande_cardmod_magic_v1_api_proto_rawDescGZIP(), []int{1}
}

// Response schema for the ListMagics request.
type ListMagicsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The collection of magics
	Magics []*Magic `protobuf:"bytes,1,rep,name=magics,proto3" json:"magics,omitempty"`
}

func (x *ListMagicsResponse) Reset() {
	*x = ListMagicsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iamnande_cardmod_magic_v1_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMagicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMagicsResponse) ProtoMessage() {}

func (x *ListMagicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iamnande_cardmod_magic_v1_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMagicsResponse.ProtoReflect.Descriptor instead.
func (*ListMagicsResponse) Descriptor() ([]byte, []int) {
	return file_iamnande_cardmod_magic_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *ListMagicsResponse) GetMagics() []*Magic {
	if x != nil {
		return x.Magics
	}
	return nil
}

var File_iamnande_cardmod_magic_v1_api_proto protoreflect.FileDescriptor

var file_iamnande_cardmod_magic_v1_api_proto_rawDesc = []byte{
	0x0a, 0x23, 0x69, 0x61, 0x6d, 0x6e, 0x61, 0x6e, 0x64, 0x65, 0x2f, 0x63, 0x61, 0x72, 0x64, 0x6d,
	0x6f, 0x64, 0x2f, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x69, 0x61, 0x6d, 0x6e, 0x61, 0x6e, 0x64, 0x65, 0x2e,
	0x63, 0x61, 0x72, 0x64, 0x6d, 0x6f, 0x64, 0x2e, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x2e, 0x76, 0x31,
	0x1a, 0x25, 0x69, 0x61, 0x6d, 0x6e, 0x61, 0x6e, 0x64, 0x65, 0x2f, 0x63, 0x61, 0x72, 0x64, 0x6d,
	0x6f, 0x64, 0x2f, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x61, 0x67, 0x69,
	0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x3c, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x67, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x15, 0xfa, 0x42, 0x12, 0x72, 0x10, 0x10, 0x03, 0x18, 0x19, 0x32, 0x0a, 0x5e, 0x5b,
	0x2d, 0x2c, 0x20, 0x5c, 0x77, 0x5d, 0x2b, 0x24, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x13,
	0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x67, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x4e, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x67, 0x69, 0x63,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x06, 0x6d, 0x61, 0x67,
	0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x69, 0x61, 0x6d, 0x6e,
	0x61, 0x6e, 0x64, 0x65, 0x2e, 0x63, 0x61, 0x72, 0x64, 0x6d, 0x6f, 0x64, 0x2e, 0x6d, 0x61, 0x67,
	0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x67, 0x69, 0x63, 0x52, 0x06, 0x6d, 0x61, 0x67,
	0x69, 0x63, 0x73, 0x32, 0xcf, 0x01, 0x0a, 0x08, 0x4d, 0x61, 0x67, 0x69, 0x63, 0x41, 0x50, 0x49,
	0x12, 0x58, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x67, 0x69, 0x63, 0x12, 0x2a, 0x2e, 0x69,
	0x61, 0x6d, 0x6e, 0x61, 0x6e, 0x64, 0x65, 0x2e, 0x63, 0x61, 0x72, 0x64, 0x6d, 0x6f, 0x64, 0x2e,
	0x6d, 0x61, 0x67, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x67, 0x69,
	0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x69, 0x61, 0x6d, 0x6e, 0x61,
	0x6e, 0x64, 0x65, 0x2e, 0x63, 0x61, 0x72, 0x64, 0x6d, 0x6f, 0x64, 0x2e, 0x6d, 0x61, 0x67, 0x69,
	0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x67, 0x69, 0x63, 0x12, 0x69, 0x0a, 0x0a, 0x4c, 0x69,
	0x73, 0x74, 0x4d, 0x61, 0x67, 0x69, 0x63, 0x73, 0x12, 0x2c, 0x2e, 0x69, 0x61, 0x6d, 0x6e, 0x61,
	0x6e, 0x64, 0x65, 0x2e, 0x63, 0x61, 0x72, 0x64, 0x6d, 0x6f, 0x64, 0x2e, 0x6d, 0x61, 0x67, 0x69,
	0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x67, 0x69, 0x63, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x69, 0x61, 0x6d, 0x6e, 0x61, 0x6e, 0x64,
	0x65, 0x2e, 0x63, 0x61, 0x72, 0x64, 0x6d, 0x6f, 0x64, 0x2e, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x67, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x61, 0x6d, 0x6e, 0x61, 0x6e, 0x64, 0x65, 0x2f, 0x63, 0x61, 0x72,
	0x64, 0x6d, 0x6f, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x61, 0x67,
	0x69, 0x63, 0x76, 0x31, 0x3b, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_iamnande_cardmod_magic_v1_api_proto_rawDescOnce sync.Once
	file_iamnande_cardmod_magic_v1_api_proto_rawDescData = file_iamnande_cardmod_magic_v1_api_proto_rawDesc
)

func file_iamnande_cardmod_magic_v1_api_proto_rawDescGZIP() []byte {
	file_iamnande_cardmod_magic_v1_api_proto_rawDescOnce.Do(func() {
		file_iamnande_cardmod_magic_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_iamnande_cardmod_magic_v1_api_proto_rawDescData)
	})
	return file_iamnande_cardmod_magic_v1_api_proto_rawDescData
}

var file_iamnande_cardmod_magic_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_iamnande_cardmod_magic_v1_api_proto_goTypes = []interface{}{
	(*GetMagicRequest)(nil),    // 0: iamnande.cardmod.magic.v1.GetMagicRequest
	(*ListMagicsRequest)(nil),  // 1: iamnande.cardmod.magic.v1.ListMagicsRequest
	(*ListMagicsResponse)(nil), // 2: iamnande.cardmod.magic.v1.ListMagicsResponse
	(*Magic)(nil),              // 3: iamnande.cardmod.magic.v1.Magic
}
var file_iamnande_cardmod_magic_v1_api_proto_depIdxs = []int32{
	3, // 0: iamnande.cardmod.magic.v1.ListMagicsResponse.magics:type_name -> iamnande.cardmod.magic.v1.Magic
	0, // 1: iamnande.cardmod.magic.v1.MagicAPI.GetMagic:input_type -> iamnande.cardmod.magic.v1.GetMagicRequest
	1, // 2: iamnande.cardmod.magic.v1.MagicAPI.ListMagics:input_type -> iamnande.cardmod.magic.v1.ListMagicsRequest
	3, // 3: iamnande.cardmod.magic.v1.MagicAPI.GetMagic:output_type -> iamnande.cardmod.magic.v1.Magic
	2, // 4: iamnande.cardmod.magic.v1.MagicAPI.ListMagics:output_type -> iamnande.cardmod.magic.v1.ListMagicsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_iamnande_cardmod_magic_v1_api_proto_init() }
func file_iamnande_cardmod_magic_v1_api_proto_init() {
	if File_iamnande_cardmod_magic_v1_api_proto != nil {
		return
	}
	file_iamnande_cardmod_magic_v1_magic_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_iamnande_cardmod_magic_v1_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMagicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iamnande_cardmod_magic_v1_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMagicsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iamnande_cardmod_magic_v1_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMagicsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_iamnande_cardmod_magic_v1_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iamnande_cardmod_magic_v1_api_proto_goTypes,
		DependencyIndexes: file_iamnande_cardmod_magic_v1_api_proto_depIdxs,
		MessageInfos:      file_iamnande_cardmod_magic_v1_api_proto_msgTypes,
	}.Build()
	File_iamnande_cardmod_magic_v1_api_proto = out.File
	file_iamnande_cardmod_magic_v1_api_proto_rawDesc = nil
	file_iamnande_cardmod_magic_v1_api_proto_goTypes = nil
	file_iamnande_cardmod_magic_v1_api_proto_depIdxs = nil
}
