BEGIN;
DROP TABLE IF EXISTS cards;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS limit_breaks;
DROP TABLE IF EXISTS magics;
DROP TYPE IF EXISTS magic_purpose;
DROP TYPE IF EXISTS refinements;
COMMIT;