BEGIN;

CREATE TABLE IF NOT EXISTS cards (
    id SERIAL NOT NULL,
    name VARCHAR UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS items (
    id SERIAL NOT NULL,
    name VARCHAR UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS limitbreaks (
    id SERIAL NOT NULL,
    name VARCHAR UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS magics (
    id SERIAL NOT NULL,
    name VARCHAR UNIQUE NOT NULL
);

COMMIT;