package magics

var (
	// magic is the collection of magic entities.
	magics = [50]*magic{
		{name: "Water", purpose: "Offensive"},
		{name: "Aero", purpose: "Offensive"},
		{name: "Bio", purpose: "Offensive"},
		{name: "Demi", purpose: "Offensive"},
		{name: "Quake", purpose: "Offensive"},
		{name: "Tornado", purpose: "Offensive"},
		{name: "Holy", purpose: "Offensive"},
		{name: "Flare", purpose: "Offensive"},
		{name: "Meteor", purpose: "Offensive"},
		{name: "Ultima", purpose: "Offensive"},
		{name: "Apocalypse", purpose: "Offensive"},
		{name: "Fire", purpose: "Offensive"},
		{name: "Fira", purpose: "Offensive"},
		{name: "Firaga", purpose: "Offensive"},
		{name: "Blizzard", purpose: "Offensive"},
		{name: "Blizzara", purpose: "Offensive"},
		{name: "Blizzaga", purpose: "Offensive"},
		{name: "Thunder", purpose: "Offensive"},
		{name: "Thundara", purpose: "Offensive"},
		{name: "Thundaga", purpose: "Offensive"},
		{name: "Esuna", purpose: "Restorative"},
		{name: "Cure", purpose: "Restorative"},
		{name: "Cura", purpose: "Restorative"},
		{name: "Curaga", purpose: "Restorative"},
		{name: "Life", purpose: "Restorative"},
		{name: "Full-Life", purpose: "Restorative"},
		{name: "Regen", purpose: "Restorative"},
		{name: "Scan", purpose: "Indirect"},
		{name: "Sleep", purpose: "Indirect"},
		{name: "Blind", purpose: "Indirect"},
		{name: "Silence", purpose: "Indirect"},
		{name: "Confuse", purpose: "Indirect"},
		{name: "Berserk", purpose: "Indirect"},
		{name: "Break", purpose: "Indirect"},
		{name: "Zombie", purpose: "Indirect"},
		{name: "Death", purpose: "Indirect"},
		{name: "Double", purpose: "Indirect"},
		{name: "Triple", purpose: "Indirect"},
		{name: "Dispel", purpose: "Indirect"},
		{name: "Protect", purpose: "Indirect"},
		{name: "Shell", purpose: "Indirect"},
		{name: "Reflect", purpose: "Indirect"},
		{name: "Float", purpose: "Indirect"},
		{name: "Drain", purpose: "Indirect"},
		{name: "Haste", purpose: "Indirect"},
		{name: "Slow", purpose: "Indirect"},
		{name: "Stop", purpose: "Indirect"},
		{name: "Meltdown", purpose: "Indirect"},
		{name: "Pain", purpose: "Indirect"},
		{name: "Aura", purpose: "Indirect"},
	}
)
