// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: iamnande/cardmod/livez/v1/api.proto

package livezv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status is the enum of allowable statuses.
type Status int32

const (
	// we fully broken
	Status_STATUS_INVALID Status = 0
	// we broken
	Status_STATUS_NOT_RUNNING Status = 1
	// we are not visibly broken
	Status_STATUS_RUNNING Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_INVALID",
		1: "STATUS_NOT_RUNNING",
		2: "STATUS_RUNNING",
	}
	Status_value = map[string]int32{
		"STATUS_INVALID":     0,
		"STATUS_NOT_RUNNING": 1,
		"STATUS_RUNNING":     2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_iamnande_cardmod_livez_v1_api_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_iamnande_cardmod_livez_v1_api_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_iamnande_cardmod_livez_v1_api_proto_rawDescGZIP(), []int{0}
}

// DescribeLivezRequest is the request model of the heartbeat endpoint.
type DescribeLivezRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DescribeLivezRequest) Reset() {
	*x = DescribeLivezRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iamnande_cardmod_livez_v1_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeLivezRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeLivezRequest) ProtoMessage() {}

func (x *DescribeLivezRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iamnande_cardmod_livez_v1_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeLivezRequest.ProtoReflect.Descriptor instead.
func (*DescribeLivezRequest) Descriptor() ([]byte, []int) {
	return file_iamnande_cardmod_livez_v1_api_proto_rawDescGZIP(), []int{0}
}

// DescribeLivezResponse is the response model of the heartbeat endpoint.
type DescribeLivezResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// status is the current status of the service.
	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=iamnande.cardmod.livez.v1.Status" json:"status,omitempty"`
}

func (x *DescribeLivezResponse) Reset() {
	*x = DescribeLivezResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iamnande_cardmod_livez_v1_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeLivezResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeLivezResponse) ProtoMessage() {}

func (x *DescribeLivezResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iamnande_cardmod_livez_v1_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeLivezResponse.ProtoReflect.Descriptor instead.
func (*DescribeLivezResponse) Descriptor() ([]byte, []int) {
	return file_iamnande_cardmod_livez_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *DescribeLivezResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_INVALID
}

var File_iamnande_cardmod_livez_v1_api_proto protoreflect.FileDescriptor

var file_iamnande_cardmod_livez_v1_api_proto_rawDesc = []byte{
	0x0a, 0x23, 0x69, 0x61, 0x6d, 0x6e, 0x61, 0x6e, 0x64, 0x65, 0x2f, 0x63, 0x61, 0x72, 0x64, 0x6d,
	0x6f, 0x64, 0x2f, 0x6c, 0x69, 0x76, 0x65, 0x7a, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x69, 0x61, 0x6d, 0x6e, 0x61, 0x6e, 0x64, 0x65, 0x2e,
	0x63, 0x61, 0x72, 0x64, 0x6d, 0x6f, 0x64, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x7a, 0x2e, 0x76, 0x31,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x16,
	0x0a, 0x14, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x7a, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x52, 0x0a, 0x15, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x7a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x39, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x21, 0x2e, 0x69, 0x61, 0x6d, 0x6e, 0x61, 0x6e, 0x64, 0x65, 0x2e, 0x63, 0x61, 0x72, 0x64, 0x6d,
	0x6f, 0x64, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x48, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x49,
	0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x01,
	0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x52, 0x55, 0x4e, 0x4e, 0x49,
	0x4e, 0x47, 0x10, 0x02, 0x32, 0x92, 0x01, 0x0a, 0x08, 0x4c, 0x69, 0x76, 0x65, 0x7a, 0x41, 0x50,
	0x49, 0x12, 0x85, 0x01, 0x0a, 0x0d, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4c, 0x69,
	0x76, 0x65, 0x7a, 0x12, 0x2f, 0x2e, 0x69, 0x61, 0x6d, 0x6e, 0x61, 0x6e, 0x64, 0x65, 0x2e, 0x63,
	0x61, 0x72, 0x64, 0x6d, 0x6f, 0x64, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x7a, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x7a, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x69, 0x61, 0x6d, 0x6e, 0x61, 0x6e, 0x64, 0x65, 0x2e,
	0x63, 0x61, 0x72, 0x64, 0x6d, 0x6f, 0x64, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x7a, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x7a, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x11, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0b, 0x12, 0x09,
	0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x69, 0x76, 0x65, 0x7a, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x61, 0x6d, 0x6e, 0x61, 0x6e, 0x64, 0x65,
	0x2f, 0x63, 0x61, 0x72, 0x64, 0x6d, 0x6f, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x6c, 0x69, 0x76, 0x65, 0x7a, 0x76, 0x31, 0x3b, 0x6c, 0x69, 0x76, 0x65, 0x7a, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_iamnande_cardmod_livez_v1_api_proto_rawDescOnce sync.Once
	file_iamnande_cardmod_livez_v1_api_proto_rawDescData = file_iamnande_cardmod_livez_v1_api_proto_rawDesc
)

func file_iamnande_cardmod_livez_v1_api_proto_rawDescGZIP() []byte {
	file_iamnande_cardmod_livez_v1_api_proto_rawDescOnce.Do(func() {
		file_iamnande_cardmod_livez_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_iamnande_cardmod_livez_v1_api_proto_rawDescData)
	})
	return file_iamnande_cardmod_livez_v1_api_proto_rawDescData
}

var file_iamnande_cardmod_livez_v1_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_iamnande_cardmod_livez_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_iamnande_cardmod_livez_v1_api_proto_goTypes = []interface{}{
	(Status)(0),                   // 0: iamnande.cardmod.livez.v1.Status
	(*DescribeLivezRequest)(nil),  // 1: iamnande.cardmod.livez.v1.DescribeLivezRequest
	(*DescribeLivezResponse)(nil), // 2: iamnande.cardmod.livez.v1.DescribeLivezResponse
}
var file_iamnande_cardmod_livez_v1_api_proto_depIdxs = []int32{
	0, // 0: iamnande.cardmod.livez.v1.DescribeLivezResponse.status:type_name -> iamnande.cardmod.livez.v1.Status
	1, // 1: iamnande.cardmod.livez.v1.LivezAPI.DescribeLivez:input_type -> iamnande.cardmod.livez.v1.DescribeLivezRequest
	2, // 2: iamnande.cardmod.livez.v1.LivezAPI.DescribeLivez:output_type -> iamnande.cardmod.livez.v1.DescribeLivezResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_iamnande_cardmod_livez_v1_api_proto_init() }
func file_iamnande_cardmod_livez_v1_api_proto_init() {
	if File_iamnande_cardmod_livez_v1_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_iamnande_cardmod_livez_v1_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeLivezRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iamnande_cardmod_livez_v1_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeLivezResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_iamnande_cardmod_livez_v1_api_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iamnande_cardmod_livez_v1_api_proto_goTypes,
		DependencyIndexes: file_iamnande_cardmod_livez_v1_api_proto_depIdxs,
		EnumInfos:         file_iamnande_cardmod_livez_v1_api_proto_enumTypes,
		MessageInfos:      file_iamnande_cardmod_livez_v1_api_proto_msgTypes,
	}.Build()
	File_iamnande_cardmod_livez_v1_api_proto = out.File
	file_iamnande_cardmod_livez_v1_api_proto_rawDesc = nil
	file_iamnande_cardmod_livez_v1_api_proto_goTypes = nil
	file_iamnande_cardmod_livez_v1_api_proto_depIdxs = nil
}
