// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: iamnande/cardmod/livez/v1/api.proto

package livezv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LivezAPIClient is the client API for LivezAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LivezAPIClient interface {
	// Check returns the status of the service
	GetLivez(ctx context.Context, in *GetLivezRequest, opts ...grpc.CallOption) (*GetLivezResponse, error)
}

type livezAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewLivezAPIClient(cc grpc.ClientConnInterface) LivezAPIClient {
	return &livezAPIClient{cc}
}

func (c *livezAPIClient) GetLivez(ctx context.Context, in *GetLivezRequest, opts ...grpc.CallOption) (*GetLivezResponse, error) {
	out := new(GetLivezResponse)
	err := c.cc.Invoke(ctx, "/iamnande.cardmod.livez.v1.LivezAPI/GetLivez", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LivezAPIServer is the server API for LivezAPI service.
// All implementations must embed UnimplementedLivezAPIServer
// for forward compatibility
type LivezAPIServer interface {
	// Check returns the status of the service
	GetLivez(context.Context, *GetLivezRequest) (*GetLivezResponse, error)
	mustEmbedUnimplementedLivezAPIServer()
}

// UnimplementedLivezAPIServer must be embedded to have forward compatible implementations.
type UnimplementedLivezAPIServer struct {
}

func (UnimplementedLivezAPIServer) GetLivez(context.Context, *GetLivezRequest) (*GetLivezResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLivez not implemented")
}
func (UnimplementedLivezAPIServer) mustEmbedUnimplementedLivezAPIServer() {}

// UnsafeLivezAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LivezAPIServer will
// result in compilation errors.
type UnsafeLivezAPIServer interface {
	mustEmbedUnimplementedLivezAPIServer()
}

func RegisterLivezAPIServer(s grpc.ServiceRegistrar, srv LivezAPIServer) {
	s.RegisterService(&LivezAPI_ServiceDesc, srv)
}

func _LivezAPI_GetLivez_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLivezRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LivezAPIServer).GetLivez(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iamnande.cardmod.livez.v1.LivezAPI/GetLivez",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LivezAPIServer).GetLivez(ctx, req.(*GetLivezRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LivezAPI_ServiceDesc is the grpc.ServiceDesc for LivezAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LivezAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iamnande.cardmod.livez.v1.LivezAPI",
	HandlerType: (*LivezAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLivez",
			Handler:    _LivezAPI_GetLivez_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iamnande/cardmod/livez/v1/api.proto",
}
