name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push New Tag Version
        uses: anothrNick/github-tag-action@1.38.0
        env:
          WITH_V: true
          RELEASE_BRANCHES: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Publish Draft Release
        uses: release-drafter/release-drafter@v5.20.0
        id: draft-release
        with:
          name: ${{ steps.tag.outputs.new_tag }}
          tag: ${{ steps.tag.outputs.new_tag }}
          version: ${{ steps.tag.outputs.new_tag }}
          publish: true
          draft: true
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Promote Release
        uses: release-drafter/release-drafter@v5.20.0
        id: release
        with:
          name: ${{ steps.tag.outputs.new_tag }}
          tag: ${{ steps.tag.outputs.new_tag }}
          version: ${{ steps.tag.outputs.new_tag }}
          publish: true
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
