name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push New Tag Version
        uses: anothrNick/github-tag-action@1.38.0
        env:
          WITH_V: true
          RELEASE_BRANCHES: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Draft Release
        uses: release-drafter/release-drafter@v5.20.0
        id: draft-release
        with:
          tag: ${{ steps.tag.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
