name: Unit

on: [ pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: make build-binary

      - name: Run Test Suite
        run: make test-unit

      - name: Record Code Coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage/unit/coverage.txt
          flags: unittests