name: Unit

# TODO: I don't like doing anything on main. Find a way to make codecove happy
#       without doing this on main.
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run Test Suite
        run: make test-unit

      - name: Record Code Coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage/unit/coverage.txt
          flags: unittests